<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE services [
  <!ELEMENT services (configurable*)>
     <!ELEMENT configurable (#PCDATA)>
        <!ATTLIST configurable
                  name      CDATA   #REQUIRED
                  address   CDATA   #REQUIRED
        >
]>
<services>
  <configurable name="mimetypes.config" address="//localhost:1099/mimetypes.config"></configurable>
  <configurable name="WorkflowServer.dsservice" address="//localhost:1099/WorkflowServer.dsservice"></configurable>
  <configurable name="WorkflowServer.config" address="//localhost:1099/WorkflowServer.config"></configurable>
  <configurable name="SearchServer.dsservice" address="//localhost:1099/SearchServer.dsservice"></configurable>
  <configurable name="Subscription.config" address="//localhost:1099/Subscription.config"></configurable>
  <configurable name="Subscription.ops" address="//localhost:1099/Subscription.ops"></configurable>
  <configurable name="directoryServiceAdminFactory" address="//localhost:1099/directoryServiceAdminFactory"></configurable>
  <configurable name="IndexServer.dsservice" address="//localhost:1099/IndexServer.dsservice"></configurable>
  <configurable name="IndexServer.ops" address="//localhost:1099/IndexServer.ops"></configurable>
  <configurable name="mailagent.config" address="//localhost:1099/mailagent.config"></configurable>
  <configurable name="RecordsMgmtHostInterface" address="//localhost:1099/RecordsMgmtHostInterface"></configurable>
  <configurable name="Common.config" address="//localhost:1099/Common.config"></configurable>
  <configurable name="ContentStore.config" address="//localhost:1099/ContentStore.config"></configurable>
  <configurable name="ftpscan.config" address="//localhost:1099/ftpscan.config"></configurable>
  <configurable name="conversion.dsservice" address="//localhost:1099/conversion.dsservice"></configurable>
  <configurable name="large_classicons.config" address="//localhost:1099/large_classicons.config"></configurable>
  <configurable name="smbscan.dsservice" address="//localhost:1099/smbscan.dsservice"></configurable>
  <configurable name="DSServer.dsservice" address="//localhost:1099/DocuShare.dsservice"></configurable>
  <configurable name="LocaleSettings.config" address="//localhost:1099/LocaleSettings.config"></configurable>
  <configurable name="DSServer.ops" address="//localhost:1099/DocuShare.ops"></configurable>
  <configurable name="NXIndexService.ops" address="//localhost:1099/NXIndexService.ops"></configurable>
  <configurable name="mailagent.ops" address="//localhost:1099/mailagent.ops"></configurable>
  <configurable name="RecordsMgmt.config" address="//localhost:1099/RecordsMgmt.config"></configurable>
  <configurable name="RecordsMgmt.dsservice" address="//localhost:1099/RecordsMgmt.dsservice"></configurable>
  <configurable name="finder.dsservice" address="//localhost:1099/finder.dsservice"></configurable>
  <configurable name="classicons.config" address="//localhost:1099/classicons.config"></configurable>
  <configurable name="finder.config" address="//localhost:1099/finder.config"></configurable>
  <configurable name="DSWebServlet.ops" address="//localhost:1099/DSWebServlet.ops"></configurable>
  <configurable name="directory.config" address="//localhost:1099/directory.config"></configurable>
  <configurable name="Amber.config" address="//localhost:1099/Amber.config"></configurable>
  <configurable name="auth.dsservice" address="//localhost:1099/auth.dsservice"></configurable>
  <configurable name="Admin.config" address="//localhost:1099/Admin.config"></configurable>
  <configurable name="AmberUtilAPI" address="//localhost:1099/AmberUtilAPI"></configurable>
  <configurable name="DSBackgroundJobService.config" address="//localhost:1099/DSBackgroundJobService.config"></configurable>
  <configurable name="directoryProviderFactory" address="//localhost:1099/directoryProviderFactory"></configurable>
  <configurable name="conversion.config" address="//localhost:1099/conversion.config"></configurable>
  <configurable name="monitor.ops" address="//localhost:1099/monitor.ops"></configurable>
  <configurable name="NXIndexService.config" address="//localhost:1099/NXIndexService.config"></configurable>
  <configurable name="PaperUI.ops" address="//localhost:1099/PaperUI.ops"></configurable>
  <configurable name="DSServer.config" address="//localhost:1099/DocuShare.config"></configurable>
  <configurable name="RoutingSlipProcessor.ops" address="//localhost:1099/RoutingSlipProcessor.ops"></configurable>
  <configurable name="DSContentExporter.config" address="//localhost:1099/DSContentExporter.config"></configurable>
  <configurable name="dsarchive.ops" address="//localhost:1099/dsarchive.ops"></configurable>
  <configurable name="WorkflowServer.ops" address="//localhost:1099/WorkflowServer.ops"></configurable>
  <configurable name="IngesterService.ops" address="//localhost:1099/IngesterService.ops"></configurable>
  <configurable name="conversion.ops" address="//localhost:1099/conversion.ops"></configurable>
  <configurable name="mailagent.dsservice" address="//localhost:1099/mailagent.dsservice"></configurable>
  <configurable name="RecordsMgmt.ops" address="//localhost:1099/RecordsMgmt.ops"></configurable>
  <configurable name="auth.config" address="//localhost:1099/auth.config"></configurable>
  <configurable name="WorkflowManager.ops" address="//localhost:1099/WorkflowManager.ops"></configurable>
  <configurable name="Subscription.dsservice" address="//localhost:1099/Subscription.dsservice"></configurable>
  <configurable name="NXIndexService.dsservice" address="//localhost:1099/NXIndexService.dsservice"></configurable>
  <configurable name="IngesterService.config" address="//localhost:1099/IngesterService.config"></configurable>
  <configurable name="dsarchive.config" address="//localhost:1099/dsarchive.config"></configurable>
  <configurable name="DSBackgroundJobService.dsservice" address="//localhost:1099/DSBackgroundJobService.dsservice"></configurable>
  <configurable name="finder.ops" address="//localhost:1099/finder.ops"></configurable>
  <configurable name="directory.dsservice" address="//localhost:1099/directory.dsservice"></configurable>
  <configurable name="AutoClassifyService.dsservice" address="//localhost:1099/AutoClassifyService.dsservice"></configurable>
  <configurable name="adminmenu.config" address="//localhost:1099/adminmenu.config"></configurable>
  <configurable name="SearchServer.config" address="//localhost:1099/SearchServer.config"></configurable>
  <configurable name="DSWebServlet.dsservice" address="//localhost:1099/DSWebServlet.dsservice"></configurable>
  <configurable name="Routing.config" address="//localhost:1099/Routing.config"></configurable>
  <configurable name="IngesterService.dsservice" address="//localhost:1099/IngesterService.dsservice"></configurable>
  <configurable name="SearchServer.ops" address="//localhost:1099/SearchServer.ops"></configurable>
  <configurable name="ftpscan.dsservice" address="//localhost:1099/ftpscan.dsservice"></configurable>
  <configurable name="thumbnail.config" address="//localhost:1099/thumbnail.config"></configurable>
  <configurable name="smbscan.config" address="//localhost:1099/smbscan.config"></configurable>
  <configurable name="dsarchive.dsservice" address="//localhost:1099/dsarchive.dsservice"></configurable>
  <configurable name="monitor.config" address="//localhost:1099/monitor.config"></configurable>
  <configurable name="Sparrow.ops" address="//localhost:1099/Sparrow.ops"></configurable>
  <configurable name="Database_JDBC.config" address="//localhost:1099/Database_JDBC.config"></configurable>
  <configurable name="ContentStore.dsservice" address="//localhost:1099/ContentStore.dsservice"></configurable>
  <configurable name="AssociatedCollectionBean" address="//localhost:1099/AssociatedCollectionBean"></configurable>
  <configurable name="IndexServer.config" address="//localhost:1099/IndexServer.config"></configurable>
  <configurable name="amber.servlet.api.ops" address="//localhost:1099/amber.servlet.api.ops"></configurable>
  <configurable name="Database_JDBC.dsservice" address="//localhost:1099/Database_JDBC.dsservice"></configurable>
</services>
